// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: indexer/ns/pb/ns.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameValueInDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NftId int64  `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId,omitempty"`
	Id    int64  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Sat   int64  `protobuf:"varint,3,opt,name=sat,proto3" json:"sat,omitempty"`
	Name  string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NameValueInDB) Reset() {
	*x = NameValueInDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_indexer_ns_pb_ns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameValueInDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameValueInDB) ProtoMessage() {}

func (x *NameValueInDB) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_ns_pb_ns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameValueInDB.ProtoReflect.Descriptor instead.
func (*NameValueInDB) Descriptor() ([]byte, []int) {
	return file_indexer_ns_pb_ns_proto_rawDescGZIP(), []int{0}
}

func (x *NameValueInDB) GetNftId() int64 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *NameValueInDB) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NameValueInDB) GetSat() int64 {
	if x != nil {
		return x.Sat
	}
	return 0
}

func (x *NameValueInDB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_indexer_ns_pb_ns_proto protoreflect.FileDescriptor

var file_indexer_ns_pb_ns_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2f, 0x6e, 0x73, 0x2f, 0x70, 0x62, 0x2f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x62, 0x2e, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x72, 0x2e, 0x6e, 0x73, 0x22, 0x5b, 0x0a, 0x0d, 0x4e, 0x61, 0x6d, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x44, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72,
	0x2f, 0x6e, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_indexer_ns_pb_ns_proto_rawDescOnce sync.Once
	file_indexer_ns_pb_ns_proto_rawDescData = file_indexer_ns_pb_ns_proto_rawDesc
)

func file_indexer_ns_pb_ns_proto_rawDescGZIP() []byte {
	file_indexer_ns_pb_ns_proto_rawDescOnce.Do(func() {
		file_indexer_ns_pb_ns_proto_rawDescData = protoimpl.X.CompressGZIP(file_indexer_ns_pb_ns_proto_rawDescData)
	})
	return file_indexer_ns_pb_ns_proto_rawDescData
}

var file_indexer_ns_pb_ns_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_indexer_ns_pb_ns_proto_goTypes = []interface{}{
	(*NameValueInDB)(nil), // 0: pb.indexer.ns.NameValueInDB
}
var file_indexer_ns_pb_ns_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_indexer_ns_pb_ns_proto_init() }
func file_indexer_ns_pb_ns_proto_init() {
	if File_indexer_ns_pb_ns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_indexer_ns_pb_ns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameValueInDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_indexer_ns_pb_ns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexer_ns_pb_ns_proto_goTypes,
		DependencyIndexes: file_indexer_ns_pb_ns_proto_depIdxs,
		MessageInfos:      file_indexer_ns_pb_ns_proto_msgTypes,
	}.Build()
	File_indexer_ns_pb_ns_proto = out.File
	file_indexer_ns_pb_ns_proto_rawDesc = nil
	file_indexer_ns_pb_ns_proto_goTypes = nil
	file_indexer_ns_pb_ns_proto_depIdxs = nil
}
